#!/bin/bash

source $(dirname $0)/easy-photos-vars
source $(dirname $0)/easy-photos-libutils

echo "moving lowres"
mv $EZPworkdir/lowres-*.jpg $EZPlowresdir/

echo "moving fullres"
mv $EZPworkdir/201?-*.jpg $EZPfullresdir/