#!/bin/bash

# defines some vars
if [ -z $1 ]; then
    EZPworkdir=$PWD
else
    EZPworkdir=$1
fi

if [ -z $(which confget) ]; then
    echo 'ERROR : look like your system is missing confget tool you should install it before running easy-photos'
    exit 1
else

    EZPlowresdir=$(confget -f $HOME/.config/easy-photos.conf -s LOCAL EZPlowresdir)
    EZPfullresdir=$(confget -f $HOME/.config/easy-photos.conf -s LOCAL EZPfullresdir)
    EZPremotelowres=$(confget -f $HOME/.config/easy-photos.conf -s REMOTE EZPremotelowres)
    EZPremotefullres=$(confget -f $HOME/.config/easy-photos.conf -s REMOTE EZPremotefullres)
fi

# make vars available
export EZPworkdir
export EZPlowresdir
export EZPfullresdir
export EZPremotefullres
export EZPremotelowres
