#!/bin/bash

if [ "-force" == "$1" ]; then
	FFLAG="-f"
fi

source $(dirname $0)/easy-photos-vars
source $(dirname $0)/easy-photos-libutils

cd ${EZPfullresdir} && rename $FFLAG 's/(\d\d\d\d-\d\d-\d\d)_(.*)\.jpg/$1\/$1_$2.jpg/' *.jpg
cd ${EZPlowresdir}  && rename $FFLAG 's/lowres-(\d\d\d\d-\d\d-\d\d)_(.*)\.jpg/$1\/lowres-$1_$2.jpg/' *.jpg
