#!/bin/bash

# defines some vars
if [ -z $1 ]; then
    EZPworkdir=$PWD
else
    EZPworkdir=$1
fi

EZPlowresdir=/media/sdcard/upload/photos/lowres
EZPfullresdir=/media/sdcard/upload/photos/fullres
EZPremotefullres=blog:/data/upload/photos/fullres
EZPremotelowres=blog:/data/upload/photos/lowres

# make vars available
export EZPworkdir
export EZPlowresdir
export EZPfullresdir
export EZPremotefullres
export EZPremotelowres
